"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

"""

def fib(n):
    if n == 0: return [0]
    x = [0,1]
    while len(x) <= n:
        x.append(x[len(x)-1] + x[len(x)-2])
    return x
