"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

"""

def fib():
    x, y = [1,2], 2 
    while x[-1] < 4000000 :
        x.append(x[len(x)-1] + x[len(x)-2])
        if not x[-1] % 2: 
            y += x[-1]
    return y 
